#!/bin/sh

bar=${1:-32}
border=8

dims=$(xdpyinfo | awk '/dimensions:/{print $2; exit}')
w=${dims%x*}; h=${dims#*x}
w=${w:-1920}; h=${h:-1080}

frame=$((2 * border))
usable=$((h - bar))
halfw=$((w / 2))
halfh=$((usable / 2))
mid=$((bar + halfh))

emit() {
	cat <<EOF
DestroyFunc $1
AddToFunc $1
+ I Resize $2p $3p
+ I Move $4p $5p
EOF
}

# Resize takes client size; Move places the decorated frame.
emit MaximizeBelowBar $((w - frame))     $((usable - frame)) 0        $bar
emit TileLeft         $((halfw - frame)) $((usable - frame)) 0        $bar
emit TileRight        $((halfw - frame)) $((usable - frame)) $halfw   $bar
emit TileTop          $((w - frame))     $((halfh - frame))  0        $bar
emit TileBottom       $((w - frame))     $((halfh - frame))  0        $mid
