env:
  TERM: xterm-256color
  TERM_PROGRAM: Alacritty
window:
  dimensions:
    columns: 120
    lines: 38
font:
  normal:
    family: Triplicate T4c
  bold:
    family: Triplicate T4c
    style: Bold
  italic:
    family: Triplicate T4c
    style: Italic
  bold_italic:
    family: Triplicate T4c
    style: Bold Italic
  size: 14.0
key_bindings:
  - { key: Key0, mods: Alt, chars: "\x1b0" }
  - { key: Key1, mods: Alt, chars: "\x1b1" }
  - { key: Key2, mods: Alt, chars: "\x1b2" }
  - { key: Key3, mods: Alt, chars: "\x1b3" }
  - { key: Key4, mods: Alt, chars: "\x1b4" }
  - { key: Key5, mods: Alt, chars: "\x1b5" }
  - { key: Key6, mods: Alt, chars: "\x1b6" }
  - { key: Key7, mods: Alt, chars: "\x1b7" }
  - { key: Key8, mods: Alt, chars: "\x1b8" }
  - { key: Key9, mods: Alt, chars: "\x1b9" }
colors:
# XTerm's default colors
   primary:
     background: '#ffffff'
     foreground: '#000000'
   normal:
     black:   '#000000'
     red:     '#cd0000'
     green:   '#00cd00'
     yellow:  '#cdcd00'
     blue:    '#0000ee'
     magenta: '#cd00cd'
     cyan:    '#00cdcd'
     white:   '#e5e5e5'
   bright:
     black:   '#7f7f7f'
     red:     '#ff0000'
     green:   '#00ff00'
     yellow:  '#ffff00'
     blue:    '#5c5cff'
     magenta: '#ff00ff'
     cyan:    '#00ffff'
     white:   '#ffffff'

