import = ["~/.alacritty.toml.local",]

[colors.bright]
black = "0x24292e"
blue = "0x005cc5"
cyan = "0x3192aa"
green = "0x22863a"
magenta = "0x5a32a3"
red = "0xcb2431"
white = "0xffffff"
yellow = "0xb08800"

[colors.normal]
black = "0x000000"
blue = "0x0366d6"
cyan = "0x0598bc"
green = "0x28a745"
magenta = "0x5a32a3"
red = "0xd73a49"
white = "0xd1d5da"
yellow = "0xdbab09"

[colors.primary]
background = "0xffffff"
foreground = "0x000000"

[env]
TERM = "xterm-256color"
TERM_PROGRAM = "Alacritty"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[[mouse.bindings]]
action = "Paste"
mods = "Command"
mouse = "Right"

[selection]
save_to_clipboard = true

[window.dimensions]
columns = 120
lines = 36

[window.padding]
x = 4
y = 4
