#!/bin/sh

progdir="$(cd "${0%/*}" && pwd -P)"
prefix="${0##*/}:"
log() { echo "$prefix" "$@" >&2; }
fatal() { log "$@"; exit 1; }

vim=0
lab=0
for a
do
	case $a in
	vim) vim=1 ;;
	lab) lab=1 ;;
	\?) fatal "usage: $0 [vim][lab]"
	esac
done

cd "$progdir" || fatal "can't change to dir: $progdir"

for i in dot.*
do
	t="$HOME/${i#dot}"
	if [ ! -e "$t" ]
	then
		ln -s "$progdir/$i" "$t"
	fi
done

if [ ! -e "$HOME/.gitignore" ]
then
	ln -s "$progdir/.gitignore" "$HOME/.gitignore"
	git config --global core.excludesfile "$HOME/.gitignore"
fi

if [ "$vim" -eq 1 ]
then
	$progdir/vim/get https://github.com/tpope/vim-commentary
	$progdir/vim/get https://github.com/tpope/vim-eunuch
	$progdir/vim/get https://github.com/tpope/vim-fugitive
	$progdir/vim/get https://github.com/tpope/vim-repeat
	$progdir/vim/get https://github.com/tpope/vim-surround

	$progdir/vim/get -o https://github.com/fatih/vim-go
fi

if [ "$lab" -eq 1 ]
then
	if [ ! -d ~/.virtualenvs/lab ]
	then
		log "creating lab virtualenv"
		python3 -m venv ~/.virtualenvs/lab
	fi

	~/.virtualenvs/lab/bin/python3 -m pip install --upgrade \
		numpy \
		matplotlib \
		pandas \
		notebook
fi
