#!/bin/sh
set -eu

: "${DOTFILES:=$HOME/dotfiles}"

case "$PATH" in
$DOTFILES/bin:*) ;;
*)               PATH="$DOTFILES/bin:$PATH"; export PATH;;
esac

{
	echo 'urlencode:'
	printf '\n' | ./bin/urlencode; echo
	printf ' ' | ./bin/urlencode; echo
	printf '!#$%%&'\''()*+,/:;=?@[]' | ./bin/urlencode; echo
	printf 'ABCDEFGHIJKLMNOPQRSTUVWXYZ' | ./bin/urlencode; echo
	printf 'abcdefghijklmnopqrstuvwxyz' | ./bin/urlencode; echo
	printf '0123456789-_.~' | ./bin/urlencode; echo
	printf '€äöå…' | ./bin/urlencode; echo

	echo 'urldecode:'
	printf '%%21%%23%%24%%25%%26%%27%%28%%29%%2A%%2B%%2C%%2F%%3A%%3B%%3D%%3F%%40%%5B%%5D' |
		./bin/urldecode; echo
	printf '%%21%%23%%24%%25%%26%%27%%28%%29%%2A%%2B%%2C%%2F%%3A%%3B%%3D%%3F%%40%%5B%%5D' |
		./bin/urlencode -d; echo
	printf '!#$%%&'\''()*+,/:;=?@[]' | ./bin/urldecode; echo
	printf 'ABCDEFGHIJKLMNOPQRSTUVWXYZ' | ./bin/urldecode; echo
	printf 'abcdefghijklmnopqrstuvwxyz' | ./bin/urldecode; echo
	printf '0123456789-_.~' | ./bin/urldecode; echo
	printf '%%E2%%82%%AC%%C3%%A4%%C3%%B6%%C3%%A5%%E2%%80%%A6' | ./bin/urldecode; echo
	echo | ./bin/urlencode -l
	echo 'line1: word1 word2 word3
line2: word1 word2 word3
line2: word1 word2 word3' | ./bin/urlencode -l
	echo | ./bin/urldecode -l
	echo 'line1%3A%20word1%20word2%20word3
line2%3A%20word1%20word2%20word3
line2%3A%20word1%20word2%20word3' | ./bin/urldecode -l

	echo
	echo 'noac:'
	./bin/noac <termcolors

	tsv='v_1_1	v_1__2	v_1___3
v_2___3	v_2_1	v_2__2
v_3__2	v_3___3	v_3_1'
	echo
	echo 'tabfmt:'
	echo "$tsv" | tabfmt
	echo "$tsv" | tabfmt -p | sed 's/$/$/'
	echo "$tsv" | tabfmt -p -d' | ' | sed 's/^/| /; s/$/ |/'
	echo 'v_1_1 v_1_2 v_1_3' | tabfmt -d' | '
	echo 'v_1_1 v_1_2 v_1_3' | tabfmt -F'[ \t][ \t]*' -d' | '

	echo
	echo 'tabmd:'
	printf 'c_1	c__2	c___3\n%s\n' "$tsv" | tabmd
	echo 'c0 | c_1,c__2,c___3
v_1_1,v_1__2,v_1___3
v_2___3,v_2_1,v_2__2
v_3__2,v_3___3,v_3_1' | tabmd -F,

	echo
	echo 'csvtab:'
	echo 'one,two,three
one,"two ,","three "","""' | csvtab
} >test.out

cat <<'EOF' >test.exp
urlencode:
%0A
%20
%21%23%24%25%26%27%28%29%2A%2B%2C%2F%3A%3B%3D%3F%40%5B%5D
ABCDEFGHIJKLMNOPQRSTUVWXYZ
abcdefghijklmnopqrstuvwxyz
0123456789-_.~
%E2%82%AC%C3%A4%C3%B6%C3%A5%E2%80%A6
urldecode:
!#$%&'()*+,/:;=?@[]
!#$%&'()*+,/:;=?@[]
!#$%&'()*+,/:;=?@[]
ABCDEFGHIJKLMNOPQRSTUVWXYZ
abcdefghijklmnopqrstuvwxyz
0123456789-_.~
€äöå…

line1%3A%20word1%20word2%20word3
line2%3A%20word1%20word2%20word3
line2%3A%20word1%20word2%20word3

line1: word1 word2 word3
line2: word1 word2 word3
line2: word1 word2 word3

noac:
Black
Red
Green
Yellow
Blue
Magenta
Cyan
White
Bright black
Bright red
Bright green
Bright yellow
Bright blue
Bright magenta
Bright cyan
Bright white

tabfmt:
v_1_1   v_1__2  v_1___3
v_2___3 v_2_1   v_2__2
v_3__2  v_3___3 v_3_1
v_1_1   v_1__2  v_1___3$
v_2___3 v_2_1   v_2__2 $
v_3__2  v_3___3 v_3_1  $
| v_1_1   | v_1__2  | v_1___3 |
| v_2___3 | v_2_1   | v_2__2  |
| v_3__2  | v_3___3 | v_3_1   |
v_1_1 v_1_2 v_1_3
v_1_1 | v_1_2 | v_1_3

tabmd:
| c\_1        | c\_\_2      | c\_\_\_3    |
|-------------|-------------|-------------|
| v\_1\_1     | v\_1\_\_2   | v\_1\_\_\_3 |
| v\_2\_\_\_3 | v\_2\_1     | v\_2\_\_2   |
| v\_3\_\_2   | v\_3\_\_\_3 | v\_3\_1     |
| c0 &#124; c\_1 | c\_\_2      | c\_\_\_3    |
|----------------|-------------|-------------|
| v\_1\_1        | v\_1\_\_2   | v\_1\_\_\_3 |
| v\_2\_\_\_3    | v\_2\_1     | v\_2\_\_2   |
| v\_3\_\_2      | v\_3\_\_\_3 | v\_3\_1     |

csvtab:
one	two	three
one	two ,	three ","
EOF

diff test.exp test.out >&2
