#!/bin/sh
# fvwm toolbar: pager left, status right

root=${DOTFILES:-$HOME/dotfiles}
fvwmroot=$root/t490/fvwm
bar=${1:-32}
status=180
# unquoted: FvwmButtons takes the rest of the line verbatim, so
# quotes would become part of the font name
font='-adobe-helvetica-medium-r-normal--20-140-100-100-p-100-iso10646-1'

dims=$(xdpyinfo | awk '/dimensions:/{print $2; exit}')
w=${dims%x*}; w=${w:-1920}
cols=$((w / 2))

cat <<EOF
*ToolBarBack #000000
*ToolBarFore #f9f5d7
*ToolBarFont $font
*ToolBarGeometry ${w}x${bar}+0+0
*ToolBarRows 1
*ToolBarColumns $cols
*ToolBarBoxSize fixed
*ToolBarFrame 0
*ToolBarPadding 0 0
*ToolBar(90x1+0+0, Frame 0, Padding 0 0, Swallow(NoHints) "FvwmPager" \
	"FvwmPager 0 4")
*ToolBar(${status}x1-0+0, Frame 0, Padding 0 0, \
	Swallow(NoHints) "ToolStatus" \
	"Exec exec $fvwmroot/statwin")
EOF
