keybinding:
  universal:
    gotoBottom: G
    scrollUpMain-alt1: <c-u>
    scrollDownMain-alt1: <c-d>

gui:
  scrollHeight: 10
  theme:
    activeBorderColor:
      - blue
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
    cherryPickedCommitFgColor:
      - blue
    cherryPickedCommitBgColor:
      - cyan
    markedBaseCommitFgColor:
      - blue
    unstagedChangesColor:
      - red
    defaultFgColor:
      - default
